[pytest]

; addopts = --headed 
;           --browser=firefox 
;           --video=on 
;           --tracing=on 
;           --screenshot=on


; addopts = --headed 
;           --browser=firefox 
;           --video=retain-on-failure 
;           --tracing=retain-on-failure 
;         ;   --screenshot=only-on-failure
;           --html=myreport.html --self-contained-html --capture=tee-sys
;           --alluredir=reports/allure-results
          